version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/kpoint_dev
      - SESSION_SECRET=your-session-secret-here
      - REPLIT_DOMAINS=localhost:3000
      - REPL_ID=k-point-local
      - ISSUER_URL=https://replit.com/oidc
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=kpoint-google@k-point-001.iam.gserviceaccount.com
      - GOOGLE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDRRqa2R9zbtXx+\nARJ2fomWn8E/EVdRsTExejLQui3mcj7kdNSjnUGBxwYup19dEauWt2aQhvHYo8Gn\n5AZ31U4J/vC+1MnoL6rrJEKsYTmXrWsqL7t9QRKDNr/4KNPIPHmjoOFOWllMn5JK\n2kC4yU6LApDwetFMJQPaqN5XUnzfFlaNVy81T0PT+aXWrQe2OQqpRWcbNSdbMkaf\nlQ3hHaroN6MfYgDmUfIH4tY3j3ygtyc5hMumUHxXOsSZ5v48+raT+a6fiYXEpwI+\nZzohjiBTZ0VQ5la29c1nt25xyDF32psjiVxdrqROPm7elJOslixAvpvEvGMpDIlT\npX5WZSmlAgMBAAECggEAE0KU0j7P4TqVMAWKPPSNVhryzoqahi6wD9UmuxX/Zm+K\nQT1NWpd88WQvOfj2alrXd2H+ovuAY4dCqeBvBfVQHtRjNLThtig46zYlmrbB9ack\nrzfAYhksin3t8flT8GA8c6Y5RhxDjq066f+nKDqCq4F7dF5hR8g6UBPtjozNaDx7\n8cE5xWkiTgTYWs8RVQe7M3xhSEkPMj7K3xZ9Q3yGfw0ClI3XfMU395XJMSNj5CwH\nJyAfh6gpIUYR0AAwQA1Re2f/ao5WjkTEUQUdf5h0AlXotiEHn+T11AA3xLqckCxb\n+uOC0tiTzOKK5uy6MPLpIa4h7Ls25vg1qcvG142boQKBgQDtKvQFHM04kaeMwImN\nL5fyBbaHSAbQEShp04tt/PSDNw4pAlzF0TBgO0oIfQCGStJvsm1HP1boCgqt64t3\ny0ynoDl//q9Em7szdCtg2jNynMaSIwNVTPWpcxNsdFuSuuuckwzcxGcjphZIf8ri\nN9aQ9/Xgh8OaZdXERrhjzDNc9QKBgQDh5LmkhOnfqapCW0hrhJFstf8bDFwNw3iH\no3eaVQcjFWoB3gQP09gBGGQOLtRxCbs8SRdG8/GsLdA5vJjuRc+xlmAIfYHcSZxD\nsHkoeFCzJ7kKGkR3j0iq4uA+0HBdK+KStD7h11CveVkTUHqSrUITVTV9QTXVglVz\nc7TcF0er8QKBgD3JvP0//a9JMy+WUb+4sItbNayU9UFr1u2LMX4cMs+knknM1cKr\nt0C68ZS4jFRwVdbH03SGaevWAeZBwXoaOwRI1/IitiLXt7O2Bj8bWd/4PDuCZ7Hn\ndPEKi/rrbZgSnqOSI/24JW7CLHgC4yaAiaQHFcXDWRB2i3SxQASwBImpAoGAbix8\nTr10w92gaNTUsXvq4bayQaL5kszvkFguEVu/K2FaXqbGHGIaTA51XmWAv9EbPP/5\nFmYMTQnbMQ3HGQ97iQXquLleCO7uBCWiMhbcZUTOfxroodeEfbRB4uEOrKKm0x6O\nPOAjPjJVO5JY9gkC3SMF/506gHQc8T5Ry7afAkECgYBCUryvIfffNEYBlTJmfp58\n755QeeGZpAPCcpHBgl39L6/lKx4w7v72ViAS7yHaK52RHSNBVwS20bD9xC9tYSXr\nabkpi0sqxr7pIIoUJ6lp7ZD0gcbhUkvZrgrAdcbS9/+2cESELIXoCWaqhUOE1rG/\nXpxhgbcz8zml/g1GKHXahw==\n-----END PRIVATE KEY-----\n
      - GOOGLE_SHEET_ID=1M7oLDmwW4b6IEq9y49LGXJ0866b5Fzn035kbK6XDrIc
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=kpoint_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: